### ISSUE TITLE
Disable TailwindCSS color when we create a color palette like gray by example

### ISSUE THREAD

**Issue by ipatate** [gregsullivan/_tw-themejson#2]
In theme.json,  if we create a palette color with same name of Tailwind color, ex : gray
```
  {
          "color": "#eee",
          "name": "Gray",
          "slug": "gray"
  }
```
All colors like gray-100, gray-200 disappear from tailwindCSS.
It's not a real bug but it's important to know that.

**Comment by gregsullivan** [comment]
Thanks for posting this issue!

Is your ideal outcome an entry for `gray` alongside `gray-[50-900]`?

**Comment by ipatate** [comment]
I think the best is to keep the current process and just add this in the documentation.

**Comment by gregsullivan** [comment]
Just out of curiosity, do you see a negative outcome associated with creating an entry for `gray` alongside `gray-[50-900]`?

**Comment by ipatate** [comment]
i don't understand ? sorry

**Comment by gregsullivan** [comment]
It currently works this way:

* `bg-gray`: From `theme.json`
* `bg-gray-[50-900]`: Removed from config

If I resolved the core problem by making it so it worked this way:

* `bg-gray`: From `theme.json`
* `bg-gray-[50-900]`: Continue using Tailwind defaults

Would that have caused problems with your workflow?

**Comment by gregsullivan** [comment]
I've updated the documentation on GitHub, adding the following line:

> If one or more of your color palette’s `slug` values matches a slug in Tailwind’s default color palette, those colors from the default palette—including all shades—will be overridden by the `color` value from your `theme.json` file.

Does that sound right to you? I'll wait a day or two before publishing the update to npm (so that if you or anyone else have feedback, I can address it without incrementing the version number a second time).

**Comment by ipatate** [comment]
yes, it's sound right.

You can add exemple :
```
{
   "slug": "white",
   "color": "#f6f6f6",
   "name": "White"
},
```
override : ```text-white bg-white...```

**Comment by gregsullivan** [comment]
Thanks for this! I'm reworking the full documentation for _tw, so I might include this there. (I want to keep the `README.md` for this project relatively terse.)

Much appreciated!
